# Generated by Django 5.0.2 on 2024-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='seo_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='seo_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='seo_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
